language: node_js
services:
  - docker
node_js:
  - 10
cache:
  directories:
    - node_modules
env:
  - DOCKER_IMAGE="emakinatr/makina-app"
script:
  - npm run lint
  - npm run build
  - npm test
after_success:
  - npm install codecov --no-save
  - codecov
deploy:
  skip_cleanup: true
  provider: script
  script: bash .travis-deploy.sh
  on:
    all_branches: true
    condition: $TRAVIS_BRANCH =~ ^develop|master$
