language: node_js
services:
  - docker
node_js:
  - 10
cache:
  directories:
    - node_modules
env:
  - DOCKER_IMAGE="emakinatr/makina-app"
script:
  # Build and test
  - npm run lint
  - npm run build
  - npm test
  # Coverage
  - npm install coveralls --no-save
  - coveralls < ./coverage/lcov.info
deploy:
  provider: script
  script: bash .travis-deploy.sh
  on:
    all_branches: true
    condition: $TRAVIS_BRANCH =~ ^develop|master$
